-- =============================================================================
-- SCRIPT DE CREACIÓN DE ESQUEMA Y POBLACIÓN DE DATOS PARA SISTEMA POS DE TIENDA
-- USUARIO: TIENDABD (o 'tienda' según tu configuración)
-- BASE DE DATOS: Oracle 21c
-- ESTILO DE TIENDA: Abarrotes / Tienda de Conveniencia (Ficticia)
-- =============================================================================

-- Desactivar salida para evitar mensajes innecesarios durante la ejecución
SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET VERIFY OFF

-- *****************************************************************************
-- 1. ELIMINAR OBJETOS EXISTENTES (OPCIONAL - SOLO SI QUIERES EMPEZAR DE CERO)
--    Si ya tienes objetos y quieres recrearlos, descomenta y ejecuta esta sección.
--    ¡ADVERTENCIA: Esto borrará todos los datos y la estructura existente!
-- *****************************************************************************
/*
DECLARE
  CURSOR c_objects IS
    SELECT object_type, object_name
    FROM user_objects
    WHERE object_type IN ('TABLE', 'VIEW', 'SEQUENCE', 'PROCEDURE', 'FUNCTION', 'PACKAGE', 'MATERIALIZED VIEW', 'TYPE', 'SYNONYM', 'INDEX', 'TRIGGER')
    AND object_name NOT LIKE 'BIN$%' -- Excluir objetos de la papelera de reciclaje
    ORDER BY CASE object_type
               WHEN 'TRIGGER' THEN 1 -- Borrar triggers antes de tablas/vistas
               WHEN 'VIEW' THEN 2
               WHEN 'TABLE' THEN 3
               WHEN 'PACKAGE' THEN 4
               WHEN 'PROCEDURE' THEN 5
               WHEN 'FUNCTION' THEN 6
               WHEN 'TYPE' THEN 7
               WHEN 'SEQUENCE' THEN 8
               ELSE 9
             END DESC, object_name;
  v_sql_stmt VARCHAR2(200);
BEGIN
  DBMS_OUTPUT.PUT_LINE('--- Eliminando objetos existentes (si los hay) ---');
  FOR obj IN c_objects LOOP
    BEGIN
      IF obj.object_type = 'TABLE' THEN
        v_sql_stmt := 'DROP ' || obj.object_type || ' "' || obj.object_name || '" CASCADE CONSTRAINTS PURGE';
      ELSIF obj.object_type = 'TYPE' THEN
        v_sql_stmt := 'DROP ' || obj.object_type || ' "' || obj.object_name || '" CASCADE';
      ELSIF obj.object_type = 'SEQUENCE' THEN
        v_sql_stmt := 'DROP ' || obj.object_type || ' "' || obj.object_name || '"';
      ELSIF obj.object_type = 'TRIGGER' THEN
        v_sql_stmt := 'DROP ' || obj.object_type || ' "' || obj.object_name || '"';
      ELSE -- VISTAS, PROCEDURES, FUNCTIONS, PACKAGES
        v_sql_stmt := 'DROP ' || obj.object_type || ' "' || obj.object_name || '"';
      END IF;

      DBMS_OUTPUT.PUT_LINE('Ejecutando: ' || v_sql_stmt);
      EXECUTE IMMEDIATE v_sql_stmt;
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al eliminar ' || obj.object_type || ' ' || obj.object_name || ': ' || SQLERRM);
    END;
  END LOOP;

  -- Vaciar la papelera de reciclaje para liberar espacio inmediatamente
  EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
  DBMS_OUTPUT.PUT_LINE('Recyclebin purged.');

  DBMS_OUTPUT.PUT_LINE('--- Eliminación de objetos completada ---');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error general durante la eliminación de objetos: ' || SQLERRM);
END;
/
*/

-- *****************************************************************************
-- 2. CREACIÓN DE SECUENCIAS
--    Definición de secuencias para generar IDs únicos y autoincrementales.
-- *****************************************************************************

CREATE SEQUENCE SEQ_PRODUCTOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROVEEDORES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORIAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VENTAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETALLE_VENTAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUENTAS_EFECTIVO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CORTES_CAJA START WITH 1 INCREMENT BY 1 NOCACHE;

DBMS_OUTPUT.PUT_LINE('Secuencias creadas.');

-- *****************************************************************************
-- 3. CREACIÓN DE TABLAS
--    Definición de las estructuras de las tablas con sus columnas, tipos de datos
--    y restricciones NOT NULL, CHECK, UNIQUE y PRIMARY KEY.
-- *****************************************************************************

-- Tabla CATEGORIAS
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA   NUMBER(10)      DEFAULT SEQ_CATEGORIAS.NEXTVAL PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR2(100)   NOT NULL UNIQUE,
    DESCRIPCION    VARCHAR2(255)
);
DBMS_OUTPUT.PUT_LINE('Tabla CATEGORIAS creada.');

-- Tabla PROVEEDORES
CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR     NUMBER(10)      DEFAULT SEQ_PROVEEDORES.NEXTVAL PRIMARY KEY,
    NOMBRE_PROVEEDOR VARCHAR2(100)   NOT NULL UNIQUE, -- Coincide con backend
    CONTACTO_PERSONA VARCHAR2(100),   -- Coincide con backend
    TELEFONO         VARCHAR2(20),
    EMAIL            VARCHAR2(100)    -- Añadido para realismo, el backend no lo usa aún.
);
DBMS_OUTPUT.PUT_LINE('Tabla PROVEEDORES creada.');

-- Tabla PRODUCTOS (Completa y compatible con el backend)
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO         NUMBER(10)      DEFAULT SEQ_PRODUCTOS.NEXTVAL PRIMARY KEY,
    CODIGO_BARRAS       VARCHAR2(50)    UNIQUE NULL,
    NOMBRE              VARCHAR2(255)   NOT NULL,
    DESCRIPCION         VARCHAR2(1000),
    UNIDAD_MEDIDA       VARCHAR2(20)    DEFAULT 'Unidad' NOT NULL,
    PRECIO_COMPRA       NUMBER(10, 2)   CHECK (PRECIO_COMPRA >= 0),
    PRECIO_VENTA        NUMBER(10, 2)   NOT NULL CHECK (PRECIO_VENTA >= 0), -- Antes PRECIO
    STOCK_ACTUAL        NUMBER(10)      NOT NULL CHECK (STOCK_ACTUAL >= 0), -- Antes STOCK
    STOCK_MINIMO        NUMBER(10)      DEFAULT 0 CHECK (STOCK_MINIMO >= 0),
    FECHA_CADUCIDAD     DATE,
    FECHA_REGISTRO      DATE            DEFAULT SYSDATE NOT NULL,
    ULTIMA_ACTUALIZACION DATE           DEFAULT SYSDATE NOT NULL,
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL CHECK (ACTIVO IN (0, 1)),
    IMAGEN_URL          VARCHAR2(255),               -- COLUMNA REQUERIDA POR EL BACKEND
    PESO_KG             NUMBER(10, 3)   CHECK (PESO_KG >= 0),
    VOLUMEN_M3          NUMBER(10, 3)   CHECK (VOLUMEN_M3 >= 0),
    ID_PROVEEDOR        NUMBER(10)      NOT NULL,
    ID_CATEGORIA        NUMBER(10)      NOT NULL, -- Requerido por la lógica
    CONSTRAINT FK_PRODUCTOS_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES PROVEEDORES(ID_PROVEEDOR),
    CONSTRAINT FK_PRODUCTOS_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIAS(ID_CATEGORIA)
);
DBMS_OUTPUT.PUT_LINE('Tabla PRODUCTOS creada.');

-- Tabla CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE     NUMBER(10)      DEFAULT SEQ_CLIENTES.NEXTVAL PRIMARY KEY,
    NOMBRE         VARCHAR2(100)   NOT NULL,
    APELLIDO       VARCHAR2(100),
    DIRECCION      VARCHAR2(255),
    TELEFONO       VARCHAR2(20),
    EMAIL          VARCHAR2(100)   UNIQUE -- Añadido para realismo
);
DBMS_OUTPUT.PUT_LINE('Tabla CLIENTES creada.');

-- Tabla VENTAS
CREATE TABLE VENTAS (
    ID_VENTA        NUMBER(10)      DEFAULT SEQ_VENTAS.NEXTVAL PRIMARY KEY,
    FECHA_VENTA     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    TOTAL_VENTA     NUMBER(10, 2)   NOT NULL CHECK (TOTAL_VENTA >= 0),
    ESTADO          VARCHAR2(50)    DEFAULT 'Completada' NOT NULL,
    ID_CLIENTE      NUMBER(10),
    CONSTRAINT FK_VENTAS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);
DBMS_OUTPUT.PUT_LINE('Tabla VENTAS creada.');

-- Tabla DETALLE_VENTAS
CREATE TABLE DETALLE_VENTAS (
    ID_DETALLE_VENTA NUMBER(10)     DEFAULT SEQ_DETALLE_VENTAS.NEXTVAL PRIMARY KEY,
    ID_VENTA         NUMBER(10)     NOT NULL,
    ID_PRODUCTO      NUMBER(10)     NOT NULL,
    CANTIDAD         NUMBER(10)     NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO  NUMBER(10, 2)  NOT NULL CHECK (PRECIO_UNITARIO >= 0),
    SUBTOTAL         NUMBER(10, 2)  NOT NULL CHECK (SUBTOTAL >= 0),
    CONSTRAINT FK_DETALLE_VENTAS_VENTA FOREIGN KEY (ID_VENTA)
        REFERENCES VENTAS(ID_VENTA) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_VENTAS_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO)
);
DBMS_OUTPUT.PUT_LINE('Tabla DETALLE_VENTAS creada.');

-- Tabla CUENTAS_EFECTIVO
CREATE TABLE CUENTAS_EFECTIVO (
    ID_CUENTA       NUMBER(10)      DEFAULT SEQ_CUENTAS_EFECTIVO.NEXTVAL PRIMARY KEY,
    NOMBRE_CUENTA   VARCHAR2(100)   DEFAULT 'Caja Principal' NOT NULL UNIQUE,
    MONTO_ACTUAL    NUMBER(10, 2)   DEFAULT 0 NOT NULL CHECK (MONTO_ACTUAL >= 0)
);
DBMS_OUTPUT.PUT_LINE('Tabla CUENTAS_EFECTIVO creada.');

-- Tabla CORTES_CAJA
CREATE TABLE CORTES_CAJA (
    ID_CORTE        NUMBER(10)      DEFAULT SEQ_CORTES_CAJA.NEXTVAL PRIMARY KEY,
    FECHA_CORTE     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    MONTO_CORTE     NUMBER(10, 2)   NOT NULL,
    VENTAS_REALIZADAS_DIA NUMBER(10) NOT NULL
);
DBMS_OUTPUT.PUT_LINE('Tabla CORTES_CAJA creada.');

-- *****************************************************************************
-- 4. CREACIÓN DE TRIGGERS (para automatizar actualizaciones de campos)
-- *****************************************************************************

-- Trigger para actualizar ULTIMA_ACTUALIZACION en PRODUCTOS
CREATE OR REPLACE TRIGGER TRG_PRODUCTOS_UPD_DATE
BEFORE UPDATE ON PRODUCTOS
FOR EACH ROW
BEGIN
    :NEW.ULTIMA_ACTUALIZACION := SYSDATE;
END;
/
DBMS_OUTPUT.PUT_LINE('Trigger TRG_PRODUCTOS_UPD_DATE creado.');

-- Trigger para calcular SUBTOTAL en DETALLE_VENTAS
CREATE OR REPLACE TRIGGER TRG_DETALLE_VENTAS_SUBTOTAL
BEFORE INSERT OR UPDATE OF CANTIDAD, PRECIO_UNITARIO ON DETALLE_VENTAS
FOR EACH ROW
BEGIN
    :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO;
END;
/
DBMS_OUTPUT.PUT_LINE('Trigger TRG_DETALLE_VENTAS_SUBTOTAL creado.');

-- *****************************************************************************
-- 5. INSERCIÓN DE DATOS DE EJEMPLO
-- *****************************************************************************

-- Insertar categorías relevantes para abarrotes
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Electrónica', 'Dispositivos y gadgets (ej. básculas, cajas registradoras).'); -- ID 1 (si no se borra)
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Alimentos Básicos', 'Granos, azúcares, aceites, etc.'); -- ID 2 (si no se borra)
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Panadería', 'Pan fresco, tortillas, pasteles.'); -- ID 3
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Lácteos y Refrigerados', 'Leche, yogurt, queso, embutidos fríos.'); -- ID 4
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Bebidas', 'Refrescos, agua, jugos, bebidas energéticas.'); -- ID 5
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Botanas y Dulces', 'Frituras, dulces, chocolates.'); -- ID 6
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Higiene y Limpieza', 'Artículos de cuidado personal y limpieza del hogar.'); -- ID 7
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Frutas y Verduras', 'Productos frescos.'); -- ID 8
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION) VALUES ('Congelados', 'Alimentos que requieren refrigeración.'); -- ID 9
DBMS_OUTPUT.PUT_LINE('Datos de ejemplo en CATEGORIAS insertados.');

-- Insertar proveedores (adaptados para el nuevo esquema NOMBRE_PROVEEDOR, CONTACTO_PERSONA, EMAIL)
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Proveedor Abarrotes SA', '5512345678', 'Juan Pérez', 'juan.perez@abarrotes.com'); -- ID 1
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Proveedor Lácteos MX', '5587654321', 'María López', 'maria.lopez@lacteos.com'); -- ID 2
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Panes La Abundancia', '5551234567', 'Pedro Ramírez', 'pedro.ramirez@pan.com'); -- ID 3
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Fábrica de Gaseosas', '5567891234', 'Laura Méndez', 'laura.mendez@gaseosas.com'); -- ID 4
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Snacks Divertidos', '5543218765', 'José Martínez', 'jose.martinez@snacks.com'); -- ID 5
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Limpieza del Hogar SRL', '5576543210', 'Ana Gómez', 'ana.gomez@limpieza.com'); -- ID 6
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Frutas y Verduras Frescas', '5598765432', 'Carlos Herrera', 'carlos.herrera@frutasverduras.com'); -- ID 7
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Carnes Premium', '5522334455', 'Elena Vargas', 'elena.vargas@carnes.com'); -- ID 8

-- Proveedores adicionales que mencionaste
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Marinela Distribuciones', '5533221100', 'Carlos Martínez', 'info@marinela.com'); -- ID 9
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Bimbo S.A. de C.V.', '5544556677', 'Ana Gómez', 'ana.gomez@bimbo.com'); -- ID 10
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Refrescos Jarrito', '5566778899', 'Luis Ramírez', 'luis.ramirez@jarrito.com'); -- ID 11
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Coca-Cola México', '5512349876', 'Martha Sánchez', 'martha.sanchez@coca-cola.com'); -- ID 12
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Tía Rosa S.A.', '5599887744', 'Jorge Hernández', 'jorge.hernandez@tiarosa.com'); -- ID 13
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Distribuidora La Fábrica', '5533445566', 'Sofía López', 'sofia.lopez@distrofabrica.com'); -- ID 14
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Snacks y Golosinas S.A.', '5511223344', 'Ricardo Torres', 'ricardo.torres@snacksygo.com'); -- ID 15
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Bebidas Refrescantes S.A.', '5577889900', 'Claudia Pérez', 'claudia.perez@bebidasref.com'); -- ID 16
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Alimentos Rápidos S.A.', '5588776655', 'Miguel Castillo', 'miguel.castillo@alimrapidos.com'); -- ID 17
INSERT INTO PROVEEDORES (NOMBRE_PROVEEDOR, TELEFONO, CONTACTO_PERSONA, EMAIL) VALUES ('Panadería y Más', '5599332211', 'Elena Morales', 'elena.morales@panymas.com'); -- ID 18
DBMS_OUTPUT.PUT_LINE('Datos de ejemplo en PROVEEDORES insertados.');


-- Insertar productos (ADAPTADOS al nuevo esquema de PRODUCTOS, con ID_CATEGORIA, IMAGEN_URL y otros campos)
-- ID_CATEGORIA mapping:
-- 1: Electrónica
-- 2: Alimentos Básicos
-- 3: Panadería
-- 4: Lácteos y Refrigerados
-- 5: Bebidas
-- 6: Botanas y Dulces
-- 7: Higiene y Limpieza
-- 8: Frutas y Verduras
-- 9: Congelados

-- PRODUCTOS - INSERTS ADAPTADOS
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Leche Entera', 'Leche pasteurizada 1L', 25.00, 10, SYSDATE + 10, 2, 4, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Leche', '7501000010001', 'Litro', 18.00, 5, 1, 1.0, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Arroz Grano Fino', 'Arroz blanco 1kg', 30.50, 4, SYSDATE + 180, 1, 2, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Arroz', '7501000020002', 'Kg', 22.00, 10, 1, 1.0, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Aceite Vegetal', 'Botella de aceite 900ml', 45.00, 20, SYSDATE + 300, 1, 2, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Aceite', '7501000030003', 'Litro', 35.00, 5, 1, 0.9, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Yogurt Fresa', 'Yogurt batido 150gr', 12.00, 3, SYSDATE + 4, 2, 4, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Yogurt', '7501000040004', 'Unidad', 8.00, 5, 1, 0.15, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Pan de Caja', 'Pan blanco 600gr', 35.00, 7, SYSDATE + 3, 3, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Pan', '7501000050005', 'Unidad', 25.00, 5, 1, 0.6, 0.002);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Frijol Negro', 'Frijol negro en bolsa de 1kg', 32.00, 15, SYSDATE + 365, 1, 2, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Frijol', '7501000060006', 'Kg', 25.00, 5, 1, 1.0, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Azúcar Refinada', 'Azúcar blanca 1kg', 26.50, 10, SYSDATE + 365, 1, 2, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Azucar', '7501000070007', 'Kg', 20.00, 5, 1, 1.0, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Queso Oaxaca', 'Queso fresco 250gr', 45.00, 5, SYSDATE + 6, 2, 4, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Queso', '7501000080008', 'Unidad', 35.00, 3, 1, 0.25, 0.0005);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Crema Ácida', 'Crema 500ml', 30.00, 6, SYSDATE + 8, 2, 4, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Crema', '7501000090009', 'Unidad', 22.00, 3, 1, 0.5, 0.0005);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Refresco Cola 2L', 'Bebida carbonatada sabor cola', 29.00, 20, SYSDATE + 180, 4, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Cola', '7501000100010', 'Unidad', 20.00, 10, 1, 2.0, 0.002);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Agua Embotellada', 'Agua natural 1L', 18.00, 25, SYSDATE + 300, 4, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Agua', '7501000110011', 'Unidad', 12.00, 10, 1, 1.0, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Bolillo', 'Pan individual fresco', 3.50, 30, SYSDATE + 1, 3, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Bolillo', '7501000120012', 'Unidad', 2.00, 10, 1, 0.1, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Pan Integral', 'Pan rebanado 600gr', 40.00, 6, SYSDATE + 4, 3, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Pan+Integral', '7501000130013', 'Unidad', 30.00, 5, 1, 0.6, 0.002);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Salchicha Viena', 'Paquete 500gr', 32.00, 8, SYSDATE + 10, 8, 4, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Salchicha', '7501000140014', 'Paquete', 25.00, 3, 1, 0.5, 0.0005);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jamón de Pavo', 'Empaque 250gr', 28.00, 7, SYSDATE + 5, 8, 4, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Jamon', '7501000150015', 'Paquete', 20.00, 3, 1, 0.25, 0.0003);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Zanahoria', 'Bolsa 1kg', 14.00, 12, SYSDATE + 3, 7, 8, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Zanahoria', '7501000160016', 'Kg', 10.00, 5, 1, 1.0, 0.002);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Papa Blanca', 'Bolsa 1kg', 18.50, 10, SYSDATE + 5, 7, 8, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Papa', '7501000170017', 'Kg', 14.00, 5, 1, 1.0, 0.002);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Papas Fritas', 'Bolsa 150gr', 16.00, 20, SYSDATE + 90, 5, 6, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Papas', '7501000180018', 'Unidad', 10.00, 8, 1, 0.15, 0.0003);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Churritos Picantes', 'Botana de maíz con chile', 14.50, 15, SYSDATE + 120, 5, 6, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Churritos', '7501000190019', 'Unidad', 9.00, 5, 1, 0.1, 0.0002);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Avena Integral', 'Bolsa de 1kg', 22.00, 9, SYSDATE + 365, 1, 2, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Avena', '7501000200020', 'Kg', 15.00, 5, 1, 1.0, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Granola Mixta', 'Con nuez, avena y pasas', 38.00, 6, SYSDATE + 300, 1, 2, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Granola', '7501000210021', 'Unidad', 28.00, 3, 1, 0.5, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Paletas de Fruta', 'Paquete 10 piezas', 25.00, 10, SYSDATE + 180, 5, 6, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Paletas', '7501000220022', 'Paquete', 18.00, 5, 1, 0.3, 0.0005);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Gomitas Ácidas', 'Bolsa 150gr', 18.00, 8, SYSDATE + 365, 5, 6, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Gomitas', '7501000230023', 'Unidad', 12.00, 4, 1, 0.15, 0.0002);

-- PRODUCTOS - Marinel/Bimbo/Jarritos/Coca-Cola/Tía Rosa (ajustados a los nuevos IDs de proveedores y categorías)
-- Proveedores IDs: Marinela(9), Bimbo(10), Jarrito(11), Coca-Cola(12), Tía Rosa(13)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Gansito Marinela', 'Paquete 60g', 15.00, 20, SYSDATE + 20, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Gansito', '7501000240024', 'Unidad', 10.00, 5, 1, 0.06, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Submarinos Marinela', 'Paquete 60g', 14.00, 18, SYSDATE + 25, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Submarino', '7501000250025', 'Unidad', 9.50, 5, 1, 0.06, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Pingüinos Marinela', 'Paquete 50g', 16.00, 22, SYSDATE + 15, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Pinguino', '7501000260026', 'Unidad', 11.00, 5, 1, 0.05, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Tortugas Marinela', 'Paquete 60g', 15.50, 10, SYSDATE + 18, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Tortuga', '7501000270027', 'Unidad', 10.50, 3, 1, 0.06, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Roles Marinela', 'Paquete 75g', 17.00, 15, SYSDATE + 30, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Roles', '7501000280028', 'Unidad', 12.00, 5, 1, 0.075, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Donitas Marinela', 'Paquete 50g', 12.00, 25, SYSDATE + 10, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Donitas', '7501000290029', 'Unidad', 8.00, 8, 1, 0.05, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Marcianos Marinela', 'Paquete 45g', 13.00, 14, SYSDATE + 12, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Marciano', '7501000300030', 'Unidad', 8.50, 4, 1, 0.045, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Barritas Marinela', 'Paquete 35g', 11.50, 20, SYSDATE + 40, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Barritas', '7501000310031', 'Unidad', 7.50, 5, 1, 0.035, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Galletas Choco Chips Marinela', 'Paquete 60g', 14.00, 19, SYSDATE + 35, 9, 6, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Galletas', '7501000320032', 'Paquete', 9.00, 5, 1, 0.06, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Cuernitos Marinela', 'Paquete 70g', 15.00, 12, SYSDATE + 20, 9, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Cuernitos', '7501000330033', 'Unidad', 10.00, 4, 1, 0.07, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Mantecadas Bimbo', 'Paquete 6 pzas', 22.00, 10, SYSDATE + 15, 10, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Mantecadas', '7501000340034', 'Paquete', 15.00, 3, 1, 0.3, 0.001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Negritos Bimbo', 'Paquete 60g', 14.00, 15, SYSDATE + 10, 10, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Negritos', '7501000350035', 'Unidad', 9.00, 5, 1, 0.06, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Pan Blanco Bimbo', 'Paquete 680g', 40.00, 25, SYSDATE + 5, 10, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Pan+Blanco', '7501000360036', 'Paquete', 30.00, 10, 1, 0.68, 0.003);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Pan Integral Bimbo', 'Paquete 680g', 42.00, 20, SYSDATE + 7, 10, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Pan+Integral+Bimbo', '7501000370037', 'Paquete', 32.00, 8, 1, 0.68, 0.003);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Conchas Bimbo', 'Paquete 70g', 18.00, 18, SYSDATE + 12, 10, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Conchas', '7501000380038', 'Unidad', 12.00, 5, 1, 0.07, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Roles de Canela Bimbo', 'Paquete 75g', 20.00, 15, SYSDATE + 20, 10, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Roles+Canela', '7501000390039', 'Unidad', 14.00, 5, 1, 0.075, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Cuernitos Bimbo', 'Paquete 70g', 17.00, 10, SYSDATE + 14, 10, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Cuernitos+Bimbo', '7501000400040', 'Unidad', 11.00, 3, 1, 0.07, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Barras de Granola Bimbo', 'Paquete 35g', 16.00, 22, SYSDATE + 40, 10, 2, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Barra+Granola', '7501000410041', 'Paquete', 10.00, 8, 1, 0.035, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Galletas Emperador Bimbo', 'Paquete 60g', 15.00, 30, SYSDATE + 45, 10, 6, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Emperador', '7501000420042', 'Paquete', 9.00, 10, 1, 0.06, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Panqués Bimbo', 'Paquete 65g', 14.50, 28, SYSDATE + 35, 10, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Panques', '7501000430043', 'Unidad', 9.50, 8, 1, 0.065, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Limón', 'Botella 600ml', 18.00, 50, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Limon', '7501000440044', 'Unidad', 12.00, 15, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Tamarindo', 'Botella 600ml', 18.00, 45, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Tamarindo', '7501000450045', 'Unidad', 12.00, 15, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Piña', 'Botella 600ml', 18.00, 40, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Piña', '7501000460046', 'Unidad', 12.00, 10, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Mango', 'Botella 600ml', 18.50, 35, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Mango', '7501000470047', 'Unidad', 12.50, 10, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Mandarina', 'Botella 600ml', 18.00, 42, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Mandarina', '7501000480048', 'Unidad', 12.00, 10, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Uva', 'Botella 600ml', 19.00, 38, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Uva', '7501000490049', 'Unidad', 13.00, 10, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Fresa', 'Botella 600ml', 18.50, 30, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Fresa', '7501000500050', 'Unidad', 12.50, 8, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Jamaica', 'Botella 600ml', 18.00, 25, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Jamaica', '7501000510051', 'Unidad', 12.00, 7, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Cereza', 'Botella 600ml', 18.00, 28, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Cereza', '7501000520052', 'Unidad', 12.00, 7, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Jarritos Durazno', 'Botella 600ml', 18.50, 33, SYSDATE + 365, 11, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=J.Durazno', '7501000530053', 'Unidad', 12.50, 8, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Coca-Cola lata', '355ml', 15.00, 100, SYSDATE + 365, 12, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Coca+Lata', '7501000540054', 'Unidad', 10.00, 20, 1, 0.355, 0.00035);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Coca-Cola botella', '600ml', 18.00, 80, SYSDATE + 365, 12, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Coca+Botella', '7501000550055', 'Unidad', 12.00, 15, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Coca-Cola zero', '600ml', 20.00, 70, SYSDATE + 365, 12, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Coca+Zero', '7501000560056', 'Unidad', 14.00, 10, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Coca-Cola botella grande', '2L', 32.00, 50, SYSDATE + 365, 12, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Coca+2L', '7501000570057', 'Unidad', 25.00, 10, 1, 2.0, 0.002);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Sprite lata', '355ml', 15.00, 90, SYSDATE + 365, 12, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Sprite+Lata', '7501000580058', 'Unidad', 10.00, 15, 1, 0.355, 0.00035);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Fanta naranja lata', '355ml', 15.00, 85, SYSDATE + 365, 12, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Fanta+Naranja', '7501000590059', 'Unidad', 10.00, 15, 1, 0.355, 0.00035);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Fanta uva botella', '600ml', 18.00, 60, SYSDATE + 365, 12, 5, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Fanta+Uva', '7501000600060', 'Unidad', 12.00, 10, 1, 0.6, 0.0006);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Conchas Tía Rosa', 'Paquete 70g', 16.00, 25, SYSDATE + 20, 13, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Tia+Rosa+Conchas', '7501000610061', 'Unidad', 10.00, 8, 1, 0.07, 0.0001);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO_VENTA, STOCK_ACTUAL, FECHA_CADUCIDAD, ID_PROVEEDOR, ID_CATEGORIA, IMAGEN_URL, CODIGO_BARRAS, UNIDAD_MEDIDA, PRECIO_COMPRA, STOCK_MINIMO, ACTIVO, PESO_KG, VOLUMEN_M3)
VALUES ('Cuernitos Tía Rosa', 'Paquete 70g', 17.50, 20, SYSDATE + 15, 13, 3, 'https://placehold.co/100x100/A0B2C8/FFFFFF?text=Tia+Rosa+Cuernitos', '7501000620062', 'Unidad', 11.50, 7, 1, 0.07, 0.0001);

DBMS_OUTPUT.PUT_LINE('Datos de ejemplo en PRODUCTOS insertados.');


--Insertar clientes (adaptados para el nuevo esquema con EMAIL)
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Ana', 'García', 'Calle Falsa 123', '5511223344', 'ana.garcia1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Luis', 'Martínez', 'Avenida Siempre Viva 45', '5599887766', 'luis.martinez1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('María', 'López', 'Colonia Centro #54', '5523456789', 'maria.lopez1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Carlos', 'Ramírez', 'Calle del Sol 678', '5534567890', 'carlos.ramirez1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Sofía', 'Hernández', 'Privada Las Palmas 22', '5545678901', 'sofia.hernandez1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Jorge', 'Pérez', 'Av. Reforma 888', '5556789012', 'jorge.perez1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Fernanda', 'Santos', 'Calle Luna 99', '5567890123', 'fernanda.santos1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Diego', 'Morales', 'Av. Insurgentes Sur 145', '5578901234', 'diego.morales1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Valeria', 'Castillo', 'Circuito Interior 303', '5589012345', 'valeria.castillo1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Andrés', 'Ruiz', 'Callejón del Agua 12', '5590123456', 'andres.ruiz1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Lucía', 'Vargas', 'Av. Universidad 456', '5501234567', 'lucia.vargas1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Ricardo', 'Gómez', 'Camino Viejo a Mixcoac 78', '5512345670', 'ricardo.gomez1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Camila', 'Navarro', 'Col. Jardines del Sur 150', '5523456701', 'camila.navarro1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Elena', 'Mendoza', 'Calle Roble 234', '5534567012', 'elena.mendoza1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Pablo', 'Fuentes', 'Av. Tláhuac 990', '5545670123', 'pablo.fuentes1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Isabela', 'Zúñiga', 'Boulevard Aeropuerto 45', '5556701234', 'isabela.zuniga1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Roberto', 'Delgado', 'Calle Periférico 789', '5567012345', 'roberto.delgado1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Alicia', 'Reyes', 'Callejón de la Amargura 1', '5570123456', 'alicia.reyes1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Tomás', 'Nieto', 'Prolongación Reforma 111', '5581234567', 'tomas.nieto1@email.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL) VALUES ('Diana', 'Campos', 'Av. Cuauhtémoc 654', '5592345678', 'diana.campos1@email.com');
DBMS_OUTPUT.PUT_LINE('Datos de ejemplo en CLIENTES insertados.');

-- Inicializar cuentas de efectivo (solo una vez)
INSERT INTO CUENTAS_EFECTIVO (NOMBRE_CUENTA, MONTO_ACTUAL) VALUES ('Caja Principal', 1000.00);
INSERT INTO CUENTAS_EFECTIVO (NOMBRE_CUENTA, MONTO_ACTUAL) VALUES ('Caja Secundaria', 500.00);
DBMS_OUTPUT.PUT_LINE('Datos de ejemplo en CUENTAS_EFECTIVO insertados.');

COMMIT;
DBMS_OUTPUT.PUT_LINE('Todos los datos insertados y commit realizado.');

SET FEEDBACK ON
SET VERIFY ON
